apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: review-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres:5432/ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002
  selector:
    app: review-service
